### ISSUE TITLE
Fallo exportación datos Dublin Core a excel ISO19115

### ISSUE THREAD

**Issue by lecianto** [Sergio-Martinez-97/unizar-vv-catmdedit#9]
**Describe the bug**
 Al realizar la exportación de un dato con estándar Dublin Core al tipo excel ISO19115, aparece un error.

**To Reproduce**

    1. Seleccionar el dato
    2. Pulsar en e botón de exportar
    3. Seleccionar casilla "formato seleccionado por el usuario"
    4. Seleccionar el estándar ISO19115 y el formato ISO Excel

**Expected behavior**
Debería realizarse la exportación correctamente, sin producirse ningún error

**Desktop:**
   OS: Ubuntu

/cc @DaniRoype @lecianto

**Comment by Sergio-Martinez-97** [comment]
#8

**Comment by Sergio-Martinez-97** [comment]
#8
